databases:
  - database_name: Clinic System (MariaDB)
    sqlalchemy_uri: "mysql+pymysql://root:@host.docker.internal:3306/clinic_system"
    expose_in_sqllab: true
    allow_run_async: true
    allow_csv_upload: false
    allow_ctas: false
    allow_cvas: false
    extra: >-
      {
        "metadata_params": {},
        "engine_params": {},
        "metadata_cache_timeout": {},
        "schemas_allowed_for_file_upload": []
      }
